### ISSUE TITLE
Addons randomly check/uncheck themselves.

### ISSUE THREAD

**Issue by Theminatar** [EloBuddy/EloBuddy.Issues#51]
When I go to check an addon to have it inject, what happens is it becomes unchecked by itself. So like if I check the addon, then scroll through my EloBuddy Addon list, I'll see that the addon is no longer check marked. This does this about 8-10 times before it finally stays checked. 

The same thing happens when the addons are injecting, I'll get into the game and notice the addon hasn't been injected. So I go back to EloBuddy and I'll see the addon is no longer check marked, so I'll have to check it, then reload the addons in game.

Addons will also be randomly check marked that I didn't even check when I'm loading into the game.

**Comment by Maxhyt** [comment]
I've met this since i first used EB. Now i have all addons in a page, won't install more.

**Comment by Theminatar** [comment]
Anyone? Maxhyt is just spamming.

**Comment by Fakhry95** [comment]
same

**Comment by megamaniko** [comment]
I think all have the same issue.. Just check it and don't scroll :D

**Comment by Hellsing** [comment]
This is a known bug with the loader which we could not resolve yet, sorry for the inconvenience

**Comment by stefsot** [comment]
fixed in loader update [0.1.6.17]

**Comment by coman3** [comment]
@stefsot seems the loader wont open now, gets stuck after updating the dependencies.... 

EDIT: Never mind just restarted my pc and working fine :)

**Comment by stefsot** [comment]
@coman3 fixed

**Comment by Theminatar** [comment]
Just wondering why this was closed if it's a known bug and hasn't been fixed? It's beyond annoying, I do appreciate the reply though Hellsing.

**Comment by coman3** [comment]
@Theminatar  "fixed in loader update [0.1.6.17]"

**Comment by Theminatar** [comment]
@coman3 My EB is fully up to date and I still have these issues, I cleared appdata as well.
